name: Check HTML File

on:
  push:
    branches:
      - main 

jobs:
  check-html-file:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if HTML file exists
      run: |
        if [ -f /Formative_1/main.html ]; then
          echo "HTML file exists"
        else
          echo "HTML file does not exist"
          exit 1
        fi
